### ISSUE TITLE
Make a script to submit the simulation as a job to gadi

### ISSUE THREAD

**Issue by jbisits** [jbisits/CabbelingExperiments#18]
See [here](https://github.com/navidcy/ASC-idealised) for how Navid setup a submission script for an Oceananigans.jl model on Gadi.

**Comment by jbisits** [comment]
Hi @navidcy, I am trying to write a [shell script](https://github.com/jbisits/CabbelingExperiments/blob/main/cabbeling_gpu_run.sh) to submit an [Oceananigans.jl model](https://github.com/jbisits/CabbelingExperiments/blob/main/cabbeling_gpu_salinitynoise.jl) to gadi. I used what you did in the [ASC-idealised model](https://github.com/navidcy/ASC-idealised/blob/main/asc.sh) as a guide but my output file does not seem to be saving where I have set it to save (or at all) as I get this error

```julia
 [ Info: Oceananigans will use 12 threads
 [ Info: Model setup
 [ Info: Setting initial conditions
 [ Info: Building DNS
 [ Info: Setting two layer initial conditions
 [ Info: Setting up simulation
 ERROR: LoadError: NetCDF error: Opening path /g/data/e14/jb2381/CabbelingExperiments/outputs/cabbeling_stepchange_nothing_5min.nc: No such file or directory (NetCDF error code: 2)
 Stacktrace:
 [1] nc_open(path::String, mode::UInt16)
 @ NCDatasets ~/.julia/packages/NCDatasets/st9Jz/src/netcdf_c.jl:274
 [2] NCDatasets.NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, memory::Nothing, attrib::Dict{Any, Any})
 @ NCDatasets ~/.julia/packages/NCDatasets/st9Jz/src/dataset.jl:217
 [3] NCDataset
 @ ~/.julia/packages/NCDatasets/st9Jz/src/dataset.jl:177 [inlined]
```

When I run the same experiment setup locally all works fine and similarly if I run the experiment in an interactive session using the VDI desktop on ARE. Have you come across this error when submitting julia jobs to gadi or have I got things in my submission script wrong? Any help would be great but only if you have time!

**Comment by navidcy** [comment]
strange...

not sure if something changed with NCDatasets.jl or something? I wasn't doing anything more special back then... perhaps the situation calls for a Zoom to debug?

do you enforce all versions of the packages to be fixed by using a Manifest.toml?

(cc @taimoorsohail)

**Comment by jbisits** [comment]
Yes I have compat entries in [TwoLayerDirectNumericalShenanigans.jl](https://github.com/jbisits/TwoLayerDirectNumericalShenanigans.jl). For NCDatasets.jl it is

```julia
NCDatasets = "0.12"
``` 
I have not changed to 0.13 yet because I remember seeing something about a bug 0.13.

It is a little strange because the `outputs` folder is correctly created but then no file to save to is there. I will try to submit a job now just in case something magic happens but if not I think you might be right about a zoom for debugging..

**Comment by navidcy** [comment]
OK, except magic happens, then try to submit a job when you only do something like:

```Julia
using NCDatasets
# This creates a new NetCDF file /tmp/test.nc.
# The mode "c" stands for creating a new file (clobber)
ds = Dataset("/tmp/test.nc","c")

# Define the dimension "lon" and "lat" with the size 100 and 110 resp.
defDim(ds,"lon",100)
defDim(ds,"lat",110)

# Define a global attribute
ds.attrib["title"] = "this is a test file"

# Define the variables temperature with the attribute units
v = defVar(ds,"temperature",Float32,("lon","lat"), attrib = OrderedDict(
    "units" => "degree Celsius"))

# add additional attributes
v.attrib["comments"] = "this is a string attribute with Unicode Ω ∈ ∑ ∫ f(x) dx"

# Generate some example data
data = [Float32(i+j) for i = 1:100, j = 1:110]

# write a single column
v[:,1] = data[:,1]

# write a the complete data set
v[:,:] = data

close(ds)
```

[Taken from NCDatasets.jl README; removed the `using DataStructures` which is unnecessary I think... try it locally first! :)]

**Comment by navidcy** [comment]
Also ensure you have the right `storage` flags in your `qsub` script for where you are trying to save...?

**Comment by navidcy** [comment]
> Yes I have compat entries in [TwoLayerDirectNumericalShenanigans.jl](https://github.com/jbisits/TwoLayerDirectNumericalShenanigans.jl). For NCDatasets.jl it is
> 
> ```julia
> NCDatasets = "0.12"
> ```
> 
> I have not changed to 0.13 yet because I remember seeing something about a bug 0.13.

NCDatasets 0.13.1 should be OK!

**Comment by jbisits** [comment]
No luck will try the [example job](https://github.com/jbisits/CabbelingExperiments/issues/18#issuecomment-1782071825) you suggest above. 

> Also ensure you have the right storage flags in your qsub script for where you are trying to save...?

I think so.. @taimoorsohail took a look and said it looked correct.

> NCDatasets 0.13.1 should be OK!

Great will set a new compat!

**Comment by navidcy** [comment]
Another thing to experiment is to use CPU() and see if it makes a difference? It shouldn't ... but who knows...

https://github.com/jbisits/CabbelingExperiments/blob/2f8bd86240400f87a824c3f706edef72894fc807/cabbeling_gpu_salinitynoise.jl#L3

**Comment by jbisits** [comment]
Running [run_nc_test.sh](https://github.com/jbisits/CabbelingExperiments/blob/main/run_nc_test.sh), which uses the example above, works. Correctly saves `"test.nc"` in `outputs` with the same PBS job settings..

**Comment by navidcy** [comment]
but your package does not..?

**Comment by jbisits** [comment]
Yep that is right, the error is that the file that is not being created

```julia
  7 ERROR: LoadError: NetCDF error: Opening path /g/data/e14/jb2381/CabbelingExperiments/outputs/cabbeling_stepchange_nothing_5min.nc: No such file or direct
    ory (NetCDF error code: 2)
  8 Stacktrace:
  9  [1] nc_open(path::String, mode::UInt16)
 10    @ NCDatasets ~/.julia/packages/NCDatasets/st9Jz/src/netcdf_c.jl:274
 11  [2] NCDatasets.NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, memory::Nothing, attrib::Dict{Any, 
    Any})
 12    @ NCDatasets ~/.julia/packages/NCDatasets/st9Jz/src/dataset.jl:217
 13  [3] NCDataset
 14    @ ~/.julia/packages/NCDatasets/st9Jz/src/dataset.jl:177 [inlined]
```

My suspicion is that it is something I have done so I am going to go back and check everything locally, then try an interactive session (where everything had been working) and see if I can find out what might be going on.

**Comment by navidcy** [comment]
Does the `outputs` exist? Not sure if NCDatasets can create the directory. Try having an empty `outputs` directory?

**Comment by jbisits** [comment]
> Does the `outputs` exist? Not sure if NCDatasets can create the directory.

Yep, the function creates the `outputs` directory separately (which it did on the first run but does not need to on subsequent runs).

>  Try having an empty `outputs` directory?

It has been on all attempts except my most recent one where the only other file in it was the `test.nc` (created from the submission script).

It is doing everything as it should in terms of naming as well as this is what the filename should be and where it should be being saved 

```julia
/g/data/e14/jb2381/CabbelingExperiments/outputs/cabbeling_stepchange_nothing_5min.nc
```

**Comment by jbisits** [comment]
I have been having some troubles with the netcdf saving locally, including seeing the same error as is occuring in the gadi submission script. I am not sure in which commit these started appearing as everything was working fine locally so will have to do some debugging. I will let you know how I get on but if once I have fixed these problems I am still not able to save on gadi I will get in touch!

**Comment by navidcy** [comment]
ok!

**Comment by jbisits** [comment]
Fixed with TwoLayerDirectNumericalShenanigans.jl v0.5.0

**Comment by navidcy** [comment]
I don't really understand what the fix was here. Link to a PR?

**Comment by jbisits** [comment]
> I'm happy that this is resolved but I don't really understand what the fix was here. Link to a PR?

Sorry I forgot to link the issue to the [PR](https://github.com/jbisits/TwoLayerDirectNumericalShenanigans.jl/pull/155).

The issue had to do with `overwrite_existing` behaviour in the [`NetcdfOutputWriter`](https://clima.github.io/OceananigansDocumentation/dev/appendix/library/#Oceananigans.OutputWriters.NetCDFOutputWriter-Tuple{Any,%20Any}) and `JLD2OutputWriter`. In previous versions of TwoLayerDirectNumericalShenanigans.jl (TLDNS) I set `overwrite_existing` to `true` by default so a file was always created or overwritten if it already exists. In TLDNS v0.4.5 I changed this default behaviour to `false` so a file is _only_ appended to not created. So when the simulation setup was run some of my custom outputs would try to save to `simulation.output_writers[:outputs].filepath` but it had not been created. The fix was to set `overwrite_existing` or more specifically the keyword argument `overwrite_saved_output = nothing` in `TLDNS_simulation_setup`

```julia
function TLDNS_simulation_setup(tldns::TwoLayerDNS, Δt::Number,
                                stop_time::Number, save_schedule::Number;
                                save_file = :netcdf,
                                output_path = SIMULATION_PATH,
                                checkpointer_time_interval = nothing,
                                cfl = 0.75,
                                diffusive_cfl = 0.75,
                                max_change = 1.2,
                                max_Δt = 1e-1,
                                density_reference_gp_height = 0,
                                overwrite_saved_output = nothing,
                                save_velocities = false)
```

to match behaviour of the source code
```julia
function NetCDFOutputWriter(model, outputs; filename, schedule,
                                          dir = ".",
                                   array_type = Array{Float64},
                                      indices = (:, :, :),
                                   with_halos = false,
                            global_attributes = Dict(),
                            output_attributes = Dict(),
                                   dimensions = Dict(),
                           overwrite_existing = nothing,
                                 deflatelevel = 0,
                                      verbose = false)
```

**Comment by jbisits** [comment]
I have however run into a [different issue](https://github.com/jbisits/TwoLayerDirectNumericalShenanigans.jl/issues/158) when saving output all of a sudden..
